=== b1f6c1c4/ProfessionalAccounting/Server/AccountingServer.BLL/Resources/Titles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Titles">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="title">
					<xs:complexType>
						<xs:choice minOccurs="0" maxOccurs="unbounded">
							<xs:element name="subTitle">
								<xs:complexType>
									<xs:attributeGroup ref="t2"/>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attributeGroup ref="t1"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:attributeGroup name="t1">
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="1000"/>
					<xs:maxInclusive value="9999"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="name" use="required" type="xs:string"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="t2">
		<xs:attribute name="id" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="01"/>
					<xs:maxInclusive value="99"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="name" use="required" type="xs:string"/>
	</xs:attributeGroup>
</xs:schema>

=== b1f6c1c4/ProfessionalAccounting/Server/AccountingServer.BLL/Resources/Titles.xml
<?xml version="1.0" encoding="UTF-8"?>
<Titles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Titles.xsd">
	<title name="资产" id="1000"/>
	<title name="库存现金" id="1001"/>
	<title name="银行存款" id="1002"/>
	<title name="其他货币资金" id="1012">
		<subTitle name="公交卡" id="1"/>
		<subTitle name="支付宝" id="3"/>
		<subTitle name="存出投资款" id="4"/>
		<subTitle name="学生卡" id="5"/>
	</title>
	<title name="交易性金融资产" id="1101">
		<subTitle name="成本" id="1"/>
		<subTitle name="公允价值变动" id="2"/>
	</title>
	<title name="应收账款" id="1122"/>
	<title name="预付账款" id="1123"/>
	<title name="其他应收款" id="1221"/>
	<title name="原材料" id="1403"/>
	<title name="库存商品" id="1405"/>
	<title name="包装物及低值易耗品" id="1412"/>
	<title name="贵金属" id="1441"/>
	<title name="持有至到期投资" id="1501">
		<subTitle name="投资成本" id="1"/>
		<subTitle name="利息调整" id="2"/>
		<subTitle name="应计利息" id="3"/>
	</title>
	<title name="持有至到期投资减值准备" id="1502"/>
	<title name="可供出售金融资产" id="1503">
		<subTitle name="成本" id="1"/>
		<subTitle name="公允价值变动" id="2"/>
	</title>
	<title name="可供出售金融资产减值准备" id="1504"/>
	<title name="长期股权投资" id="1511">
		<subTitle name="成本" id="1"/>
		<subTitle name="损益调整" id="2"/>
		<subTitle name="其他权益变动" id="3"/>
	</title>
	<title name="长期股权投资减值准备" id="1512"/>
	<title name="固定资产" id="1601"/>
	<title name="累计折旧" id="1602"/>
	<title name="固定资产减值准备" id="1603"/>
	<title name="在建工程" id="1604"/>
	<title name="工程物资" id="1605"/>
	<title name="固定资产清理" id="1606"/>
	<title name="无形资产" id="1701"/>
	<title name="累计摊销" id="1702"/>
	<title name="无形资产减值准备" id="1703"/>
	<title name="待处理财产损溢" id="1901"/>
	<title name="负债" id="2000"/>
	<title name="短期借款" id="2001"/>
	<title name="应付账款" id="2202"/>
	<title name="预收账款" id="2203"/>
	<title name="应付职工薪酬" id="2211"/>
	<title name="应交税费" id="2221">
		<subTitle name="应交个人所得税" id="5"/>
	</title>
	<title name="其他应付款" id="2241">
		<subTitle name="贷记卡" id="1"/>
	</title>
	<title name="所有者权益" id="4000"/>
	<title name="实收资本" id="4001"/>
	<title name="盈余公积" id="4101"/>
	<title name="本年利润" id="4103"/>
	<title name="损益" id="6000"/>
	<title name="主营业务收入" id="6001">
		<subTitle name="奖学金" id="1"/>
	</title>
	<title name="其他业务收入" id="6051"/>
	<title name="公允价值变动损益" id="6101">
		<subTitle name="交易性金融资产" id="1"/>
	</title>
	<title name="投资收益" id="6111">
		<subTitle name="长期股权投资" id="1"/>
		<subTitle name="交易性金融资产" id="2"/>
		<subTitle name="可供出售金融资产" id="5"/>
		<subTitle name="持有至到期投资" id="6"/>
	</title>
	<title name="营业外收入" id="6301">
		<subTitle name="处置固定资产利得" id="1"/>
		<subTitle name="无法支付的应付款项" id="2"/>
		<subTitle name="捐赠利得" id="3"/>
		<subTitle name="上级拨入资金" id="4"/>
		<subTitle name="其他" id="99"/>
	</title>
	<title name="主营业务成本" id="6401"/>
	<title name="其他业务支出" id="6402"/>
	<title name="管理费用" id="6602">
		<subTitle name="水电气费" id="1"/>
		<subTitle name="房租" id="2"/>
		<subTitle name="餐费" id="3"/>
		<subTitle name="通讯费" id="4"/>
		<subTitle name="医药费" id="5"/>
		<subTitle name="福利费" id="6"/>
		<subTitle name="折旧费" id="7"/>
		<subTitle name="交通运输费" id="8"/>
		<subTitle name="办公费" id="9"/>
		<subTitle name="招待费" id="10"/>
		<subTitle name="无形资产摊销" id="11"/>
		<subTitle name="其它" id="99"/>
	</title>
	<title name="财务费用" id="6603">
		<subTitle name="利息支出" id="1"/>
		<subTitle name="利息收入" id="2"/>
		<subTitle name="汇兑损溢" id="3"/>
		<subTitle name="金融机构手续费" id="4"/>
		<subTitle name="其他费用" id="99"/>
	</title>
	<title name="资产减值损失" id="6701">
		<subTitle name="长期投资减值损失" id="4"/>
		<subTitle name="固定资产减值损失" id="5"/>
		<subTitle name="无形资产减值损失" id="6"/>
		<subTitle name="持有至到期投资减值损失" id="9"/>
	</title>
	<title name="营业外支出" id="6711">
		<subTitle name="处置固定资产净损失" id="1"/>
		<subTitle name="罚没及滞纳金支出" id="8"/>
		<subTitle name="捐赠支出" id="9"/>
		<subTitle name="非常损失" id="10"/>
	</title>
</Titles>
